#deploy the home-task container
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: home-task
  labels:
    app: home-task
spec:
  replicas: 3
  # The number of old deployments you want to keep around
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: home-task
  template:
    metadata:
      labels:
        app: home-task
    # details of what container(s) will actually be run in this pod
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      # deploys this custom image from Docker Hub
      - image: danishsh/home-task:latest
        # download a fresh copy of the image if available, even if it has the same version label
        imagePullPolicy: IfNotPresent
        name: home-task
        #reserving resources from our cluster
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        ports:
        - containerPort: 80
